language: objective-c
osx_image: xcode9.1

env:
  - PLATFORM="ios" SCHEME="Spine-iOS" DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.0"
  - PLATFORM="tvos" SCHEME="Spine-tvOS" DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0"
  - PLATFORM="mac" SCHEME="Spine-macOS" DESTINATION="platform=macOS,arch=x86_64"

before_script:
  - carthage bootstrap --platform $PLATFORM
script:
  - xcodebuild -project Spine.xcodeproj -scheme $SCHEME -destination "$DESTINATION" build test
